name: SimplePolls
version: '${version}'
main: me.jrb326.simplePolls.SimplePolls
api-version: '1.21'
permissions:
  simplepolls.use:
    description: 'Access to view and vote on polls'
    default: true
  simplepolls.createpoll:
    description: Allows creating new polls
    default: op
